/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ashwin' at '8/26/16 4:21 PM' with Gradle 2.13
 *
 * @author ashwin, @date 8/26/16 4:21 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
